#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Feb 26, 2025 08:08:55 PM +1300  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import gui_support

_bgcolor = 'SystemButtonFace'
_fgcolor = 'SystemWindowText'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: gui_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'vista.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('vista')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class MainWindow:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("758x571+448+159")
        top.minsize(120, 1)
        top.maxsize(3844, 1041)
        top.resizable(1,  1)
        top.title("R5 Desktop Wallet")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='SystemButtonFace'
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.sub_menu = tk.Menu(self.menubar, activebackground='#d9d9d9'
                ,activeborderwidth=1, activeforeground='black'
                ,background='SystemButtonFace', borderwidth=1
                ,disabledforeground='#b4b4b4', font="-family {Segoe UI} -size 9"
                ,foreground='SystemWindowText', tearoff=0)
        self.menubar.add_cascade(compound='left', font="TkMenuFont", label='File'
                ,menu=self.sub_menu, )
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Create Wallet...')
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Load Wallet...')
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Close Wallet...', state="disabled", )
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Close All Wallets...', state="disabled", )
        self.sub_menu.add_separator()
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Settings...')
        self.sub_menu.add_separator()
        self.sub_menu.add_command(compound='left', font="TkMenuFont"
                ,label='Exit')
        self.sub_menu1 = tk.Menu(self.menubar, activebackground='#d9d9d9'
                ,activeborderwidth=1, activeforeground='black'
                ,background='SystemButtonFace', borderwidth=1
                ,disabledforeground='#b4b4b4', font="-family {Segoe UI} -size 9"
                ,foreground='SystemWindowText', tearoff=0)
        self.menubar.add_cascade(compound='left', font="TkMenuFont", label='Node'
                ,menu=self.sub_menu1, )
        self.sub_menu1.add_command(compound='left', font="TkMenuFont"
                ,label='Node Console...')
        self.sub_menu1.add_command(compound='left', font="TkMenuFont"
                ,label='JS Console...')
        self.sub_menu12 = tk.Menu(self.menubar, activebackground='#d9d9d9'
                ,activeborderwidth=1, activeforeground='black'
                ,background='SystemButtonFace', borderwidth=1
                ,disabledforeground='#b4b4b4', font="-family {Segoe UI} -size 9"
                ,foreground='SystemWindowText', tearoff=0)
        self.menubar.add_cascade(compound='left', font="TkMenuFont", label='Help'
                ,menu=self.sub_menu12, )
        self.sub_menu12.add_command(compound='left', font="TkMenuFont"
                ,label='About')

class Settings:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("661x387+471+300")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("R5 Wallet Settings")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        _style_code()
        self.TButton3 = ttk.Button(self.top)
        self.TButton3.place(relx=0.015, rely=0.827, height=25, width=136)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Load Settings File...''')
        self.TButton3.configure(compound='left')

        self.TButton4 = ttk.Button(self.top)
        self.TButton4.place(relx=0.015, rely=0.904, height=25, width=136)
        self.TButton4.configure(takefocus="")
        self.TButton4.configure(text='''Save Settings File...''')
        self.TButton4.configure(compound='left')

        self.TButton1 = ttk.Button(self.top)
        self.TButton1.place(relx=0.862, rely=0.904, height=25, width=76)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Save''')
        self.TButton1.configure(compound='left')

        self.TButton2 = ttk.Button(self.top)
        self.TButton2.place(relx=0.741, rely=0.904, height=25, width=76)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Cancel''')
        self.TButton2.configure(compound='left')

        self.TNotebook2 = ttk.Notebook(self.top)
        self.TNotebook2.place(relx=0.015, rely=0.026, relheight=0.791
                , relwidth=0.974)
        self.TNotebook2.configure(takefocus="")
        self.TNotebook2_t1 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t1, padding=3)
        self.TNotebook2.tab(0, text='''Application''', compound="left"
                ,underline='''-1''', )
        self.TNotebook2_t1.configure(cursor="fleur")
        self.TNotebook2_t1.configure(highlightcolor="SystemWindowText")
        self.TNotebook2_t2 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t2, padding=3)
        self.TNotebook2.tab(1, text='''Wallet''', compound="left"
                ,underline='''-1''', )
        self.TNotebook2_t2.configure(highlightcolor="SystemWindowText")
        self.TNotebook2_t3 = tk.Frame(self.TNotebook2)
        self.TNotebook2.add(self.TNotebook2_t3, padding=3)
        self.TNotebook2.tab(2, text='''Node''', compound="left"
                ,underline='''-1''', )
        self.TNotebook2_t3.configure(highlightcolor="SystemWindowText")

class JSConsole:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+470+263")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("JS Console")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

class NodeConsole:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("600x450+530+241")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("Node Console")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

class About:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("275x203+508+238")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("About R5 Wallet")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

def start_up():
    gui_support.main()

if __name__ == '__main__':
    gui_support.main()




